export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_SAVE_SHIPPING_ADRESSE = 'CART_SAVE_SHIPPING_ADRESSE'
export const CART_SAVE_PAYMENT = 'CART_SAVE_PAYMENT'
export const FETCH_CART_ITEMS_SUCCESS = "FETCH_CART_ITEMS_SUCCESS"
export const FETCH_CART_ITEMS_FAIL = "FETCH_CART_ITEMS_FAIL"