// constants/dashboardConstants.js

export const FETCH_OVERVIEW_DATA_REQUEST = 'FETCH_OVERVIEW_DATA_REQUEST';
export const FETCH_OVERVIEW_DATA_SUCCESS = 'FETCH_OVERVIEW_DATA_SUCCESS';
export const FETCH_OVERVIEW_DATA_FAIL = 'FETCH_OVERVIEW_DATA_FAIL';

export const FETCH_RECENT_ORDERS_REQUEST = 'FETCH_RECENT_ORDERS_REQUEST';
export const FETCH_RECENT_ORDERS_SUCCESS = 'FETCH_RECENT_ORDERS_SUCCESS';
export const FETCH_RECENT_ORDERS_FAIL = 'FETCH_RECENT_ORDERS_FAIL';

export const FETCH_TOP_SELLING_PRODUCTS_REQUEST = 'FETCH_TOP_SELLING_PRODUCTS_REQUEST';
export const FETCH_TOP_SELLING_PRODUCTS_SUCCESS = 'FETCH_TOP_SELLING_PRODUCTS_SUCCESS';
export const FETCH_TOP_SELLING_PRODUCTS_FAIL = 'FETCH_TOP_SELLING_PRODUCTS_FAIL';

export const FETCH_USER_ACTIVITY_REQUEST = 'FETCH_USER_ACTIVITY_REQUEST';
export const FETCH_USER_ACTIVITY_SUCCESS = 'FETCH_USER_ACTIVITY_SUCCESS';
export const FETCH_USER_ACTIVITY_FAIL = 'FETCH_USER_ACTIVITY_FAIL';

export const GET_REVENUE_REQUEST = 'GET_REVENUE_REQUEST';
export const GET_REVENUE_SUCCESS = 'GET_REVENUE_SUCCESS';
export const GET_REVENUE_FAIL = 'GET_REVENUE_FAIL';
